feat(new sink): Initial `azure_monitor_logs` sink
timberio/vector pull request #2811
Opened 2020-06-13 15:51 UTC by nazar554

Solves #1808 
Will add validations for configuration and unit tests

2020-06-13 19:05 UTC, nazar554 commented
Right now I assume by default that events have `timestamp` field that is ISO8601. Is there a way to make sure that it's the correct field and it's not using Unix format?

There seems to be an issue when a single event is batched in a JSON array. Azure seems to ignore the timestamp field, maybe because I don't drop milliseconds (although it works fine when there are two or more events)

2020-06-16 23:17 UTC, lukesteensen commented
> Right now I assume by default that events have `timestamp` field that is ISO8601. Is there a way to make sure that it's the correct field and it's not using Unix format?

By default, events get a timestamp field with an actual `Timestamp` value, not just a string. But that can often be overwritten with user data that can be a string, so it's hard to guarantee anything. Most sinks will read that field and check the type before using it, which it looks like you're doing.

> There seems to be an issue when a single event is batched in a JSON array. Azure seems to ignore the timestamp field, maybe because I don't drop milliseconds (although it works fine when there are two or more events)

That is odd. I didn't see anything that should behave differently with an array of one event.

2020-06-17 11:15 UTC, nazar554 commented
@lukesteensen 

> Is there some local version of this service that we could add to our integration tests?

I don't know one, you need to have a Azure Log Analytics service in order to obtain `shared_key` and `customer_id`. However, there is free 5 Gb per month plan, so if you have an Azure subscription then it's possible to test this for fee.

> That is odd. I didn't see anything that should behave differently with an array of one event.

I think it's the behavior of the Azure Log Analytics. [Official documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api) suggests a `YYYY-MM-DDThh:mm:ssZ` date format, but if you actually view some logs on Azure Portal it seems they have milliseconds there. It's possible that docs were not updated.
By default `impl Serialize` does nanosecond precision and this makes Azure drop the timestamp entirely (it uses the ingestion time instead).
 So I added one more commit where I format the date manually and use `chrono::SecondsFormat::Millis`.

> We'll also want to add docs, but that can happen in a followup PR.

I think I can add docs as well, I'll try to use some existing sink as a reference

2020-08-23 22:15 UTC, nazar554 commented
@jamtur01 I am not sure how to build & test the docs, should I clone and build [`timberio/vector-website`](https://github.com/timberio/vector-website) ?

2020-08-23 22:25 UTC, jamtur01 commented
@nazar554 I am not 100% sure how to test off a branch - @binarylogic?

2020-08-28 17:18 UTC, nazar554 commented
Anything else I need to do here? Should I also update `vector.spec.toml`?

2020-08-31 19:49 UTC, lukesteensen commented
@nazar554 That file gets updated automatically from the config definitions in `.meta/`, so you should be good there.

Once @binarylogic is able to help out with testing the docs I'll make another pass and see if there are any remaining blockers. Thanks again for opening this! Excited to get it merged.

2020-08-31 19:51 UTC, binarylogic commented
@nazar554 the docs look good. As long as `make check-meta` works (which is tested in the CI check workflow), then we're good. No need to do anything with the generated files.

2020-10-02 22:27 UTC, lukesteensen commented
@binarylogic it looks like something is up with `check-meta` here. Is there something that needs to be updated in the docs?

2020-10-02 22:28 UTC, jamtur01 requested changes
One minor issue.

2020-10-02 22:28 UTC, jamtur01 commented on .meta/sinks/azure_monitor_logs.toml.erb
> +  namespace: "sinks.azure_monitor_logs.options",
This needs:

```
enabled_default: false,
```

With the appropriate `true` or `false` value. That'll fix the failing test.

2020-10-02 22:30 UTC, lukesteensen approved these changes
This is looking good to me! If we can get CI green then I think we're ready to merge.

Thanks for your patience with this @nazar554, and apologies for it lingering so long. We really appreciate the contribution!

2020-10-03 17:12 UTC, jamtur01 requested changes
Looks like some test failures in the CI run.

2020-10-03 23:27 UTC, jamtur01 approved these changes
LGTM.

2020-10-03 23:33 UTC, jamtur01 commented
@nazar554 I just merged `master` into the branch because there are some CI changes and I want to make sure the merge goes smooth. Will merge post that.

2020-10-04 00:09 UTC, jamtur01 commented
bors merge

2020-10-04 00:09 UTC, closed without merging