chore: Update contributing testing documentation
timberio/vector pull request #3652
Opened 2020-08-31 19:48 UTC by binarylogic

While reviewing https://github.com/timberio/vector/pull/3634/files, I noticed we don't elaborate on how to unit and integration test, so I decided to add it here, among other testing aspects.

2020-09-13 16:05 UTC, jamtur01 commented on CONTRIBUTING.md
> +You can invoke the [test hardness][urls.vector_test_harness] by commenting on
harness. :)

2020-09-13 16:07 UTC, jamtur01 commented on CONTRIBUTING.md
> +- [ ] The service must be configured on a unique port that configured through an
The service must be configured on a unique port that *is* configured through an

2020-09-13 16:09 UTC, jamtur01 requested changes
Comments inline.

2020-09-13 16:09 UTC, jamtur01 commented on CONTRIBUTING.md
> +- [ ] Add a `test-integration-<name>` to Vector's [`Makefile`](/Makefile) and
that it starts the service...

2020-09-13 16:09 UTC, jamtur01 commented on CONTRIBUTING.md
> +[Vector's test hardness][urls.vector_test_harness]. This is a complex testing
harness

2020-09-13 16:15 UTC, binarylogic commented on CONTRIBUTING.md
> +You can invoke the [test hardness][urls.vector_test_harness] by commenting on
Ha ha, fixed.

2020-09-14 18:24 UTC, jszwedko approved these changes
Lost track of this one, looks good!

2020-09-14 18:25 UTC, jszwedko commented
Or I guess I didn't lose track, I was looking at the PR open time rather than review request time :smile:

2020-09-14 20:20 UTC, merged