chore: Update platform and component descriptions
timberio/vector pull request #3790
Opened 2020-09-09 22:56 UTC by binarylogic

This change aims to update all of our platform and component descriptions. I've rewritten these by hand, but was inspired by their previous descriptions.

- [X] Platform descriptions
- [ ] Source descriptions
- [ ] Sink descriptions

2020-09-09 23:08 UTC, jamtur01 requested changes
Some spelling and grammar.

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_aws_cloudwatch.toml
> +automatically integration with AWS infrastructure to help you monitor \
integration should be integrates.

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_aws_cloudwatch.toml
> +cloud infrastructure, services, and applications thourgh logs, metrics, \
through.

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_aws_cloudwatch.toml
> +traces, and other operatinal data.\
operational.

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_datadog.toml
> +[Datadog][urls.datadog] is a managed monitoring service for cloud-based \
Cloud

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_datadog.toml
> +applications. It allows you to monior servers, databases, and other services \
monitor

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_docker.toml
> +infrastructure, making your application and services portable. This reduces \
applications

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_gcp_stackdriver.toml
> +Cloud's embedded monitoring suite designed to monitor cloud infrastructure, \
Cloud

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_kafka.toml
> +a distributed commit log, similar to publish-subscribe messaging systems. \
Is is

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_kafka.toml
> +makes it an excellent candidate for durabily streaming logs, metrics, traces, \
durably

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_kubernetes.toml
> +you to manage and deploy applicationd and services across a variable number \
applications

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_prometheus.toml
> +unique pull-based model where Prometheus scrapes upstream service endpoints \
-unique

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_prometheus.toml
> +reliability, making it well suited for cloud-based environments where metrics \
Cloud-based

2020-09-09 23:08 UTC, jamtur01 commented on .meta/_partials/descriptions/_statsd.toml
> +data where it is widely supported by a variety of metrics solutions.\
where -> and

2020-09-10 17:50 UTC, jszwedko reviewed
Thanks for running through these!

2020-09-10 17:50 UTC, jszwedko commented on .meta/_partials/descriptions/_datadog.toml
> +through a SaaS-based monitoring platform.\
I'd probably avoid abbreviations and do `Software-as-a-Service` if it isn't previously defined and abbreviated in the content.

2020-10-14 17:57 UTC, jamtur01 commented
@binarylogic Should this be closed in light of cue updates?

2020-10-14 17:58 UTC, binarylogic commented
Yep

2020-10-14 17:58 UTC, closed without merging