chore(ci): Update localstack
timberio/vector pull request #4591
Opened 2020-10-15 22:13 UTC by jszwedko

Updates to latest localstack tag. I need this for some of the S3+SQS
work, but figured I'd do it separately.

The biggest change is that localstack now exposes all services on the
same port, 4566, simplifying our setup.

There are a couple of more test failures I still need to look into.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

2020-10-19 21:26 UTC, jamtur01 requested changes
Looks fine other than the two elastic_response errors?

2020-10-19 21:59 UTC, jszwedko commented
Oops, I thought I checked that we weren't using those is the `elasticsearch` sink, but I was incorrect. I'll update.

2020-10-20 16:38 UTC, jamtur01 approved these changes
LGTM

2020-10-21 06:29 UTC, fanatid commented
Can we merge it? It would be great to update localstack before https://github.com/timberio/vector/pull/2755

2020-10-21 13:20 UTC, jszwedko commented
@fanatid :+1: I was just hoping to get one more review for the rust changes.

2020-10-21 13:23 UTC, fanatid approved these changes
Thanks for removing `elastic_responses`! This was the last dependency that required an old http crate.

2020-10-21 13:35 UTC, merged