fix(ci): Fix unset $PUSH for build-docker.sh
timberio/vector pull request #4764
Opened 2020-10-26 20:15 UTC by jszwedko

Resolves
https://github.com/timberio/vector/commit/26be119ac6c506cd50001b5fdc94adafdecb0f2d#r43596614

I opted to use the eval syntax mentioned in
http://mywiki.wooledge.org/BashFAQ/050#I_only_want_to_pass_options_if_the_runtime_data_needs_them
to still allow for quoting here to satsify shellcheck. This also seems
preferable to the field splitting example there (which isn't relevant in
our case since it is a single argument, but could be in other uses of
`${FOO+'--bar' 'baz'}` expansions).

Thanks for catching that @MOZGIII !

2020-10-28 20:52 UTC, MOZGIII commented
I'd rather avoid using `eval`, it can be very surprising. Why don't we use just bash arrays instead? It's going to be much easier to understand. I take a stab at it!

2020-10-29 14:23 UTC, jszwedko commented
@MOZGIII that'd be great if you already have an idea of what it'd look like. I feel like I always struggle with bash arrays and building commands like this.

2020-11-06 09:46 UTC, MOZGIII requested changes
I created the https://github.com/timberio/vector/pull/4900 with the bash arrays

2020-11-06 14:57 UTC, jszwedko commented
:+1: Closing this in-lieu of #4900

2020-11-06 14:58 UTC, closed without merging