feat(kubernetes_logs source): Add ingestion timestamp
timberio/vector pull request #4795
Opened 2020-10-28 20:19 UTC by MOZGIII

This PR adds filling the ingestion timestamp to the `kubernetes_logs` source.

2020-10-30 22:23 UTC, lukesteensen requested changes
The `file` source should be adding a `timestamp` itself, but it looks like it does not do that currently. I'd rather we add this functionality there rather than for k8s specifically. I'm also not sure we need to allow overriding the key.

2020-10-30 23:04 UTC, MOZGIII commented
Kubernetes adds it's own `timestamp`, and adding the time when we picked up the message is not meaningful for most of the users (they want to see the time of the event as in the log file).

In the `file` source, this already happens, but it's hidden in this line: https://github.com/timberio/vector/blob/b036f347049844f500d2bcb3ebb460c3d6d41d2c/src/sources/file.rs#L310

2020-11-05 23:02 UTC, jamtur01 commented
@MOZGIII What's the status here?

2020-11-05 23:06 UTC, MOZGIII commented
> @MOZGIII What's the status here?

I want to talk with @lukesteensen about this, seems like there was a bit of confusion here, but it should be easy to resolve.

2020-11-09 16:26 UTC, lukesteensen approved these changes
Ah, I see. That makes sense.

2020-11-21 14:05 UTC, merged