feat(redis sink source) support for redis #3319
timberio/vector pull request #5199
Opened 2020-11-24 09:28 UTC by shumin1027

I creat a plugin to support redis(list、channel) as a data source and sink

the example config:
```toml
[sources.in]
type = "redis"
url = "redis://127.0.0.1/0"
key = "vector:in"
data_type = "list"

[sinks.out]
type = "redis"
inputs = ["in"]
url = "redis://127.0.0.1/0"
key = "vector:out"
data_type = "channel"
encoding.codec = "json"
```

2020-11-24 15:13 UTC, jamtur01 commented on .gitignore
> +Cargo.lock
Was this change intended? Either way, the file needs to end in a new line.

2020-11-24 15:14 UTC, jamtur01 commented on .gitlab-ci.yml
> +stages:
Also, this file seems inadvertently added.

2020-11-24 15:15 UTC, jamtur01 commented on Cargo.toml
> +shutdown-tests = ["sources", "sinks-console", "sinks-prometheus", "sinks-blackhole", "unix", "rdkafka", "transforms-log_to_metric", "transforms-lua"]
The spaces between the items also seem to be added inadvertently.

2020-11-24 15:15 UTC, jamtur01 commented on src/sinks/redis.rs
> +                // self.in_flight.push(Box::pin(async move {
Any reason for the large blocks of code commented out?

2020-11-24 15:16 UTC, jamtur01 commented on src/sources/redis/list.rs
> +        // let mut conn = client.get_async_connection().await.expect("failed to get redis async connection!");
line commented out?

2020-11-24 15:16 UTC, jamtur01 commented on src/sources/redis/list.rs
> +    // event.as_mut_log().insert("redis_key", key);
Same?

2020-11-24 15:16 UTC, jamtur01 commented on src/sources/redis/mod.rs
> +    // let mut conn = client.get_connection()?;
Same?

2020-11-24 15:17 UTC, jamtur01 commented
@shumin1027 Thanks for your contribution! I put some high-level comments in about the PR overall.

2020-11-25 02:11 UTC, jamtur01 commented
@shumin1027 Hi! Thanks for the updates. Can you please also make sure your commits are signed so our DCO is satisfied? Thanks!

2020-11-25 02:20 UTC, jamtur01 commented
There are some failed formatting checks - you can run all of those locally before you push if that helps.

2020-11-25 04:51 UTC, shumin1027 commented
@jamtur01 Thanks for your suggestions，I will remove the unused commented lines and fmt code

2020-11-25 13:01 UTC, fanatid requested changes
While it's ok for initial implementation do not have internal events I think it will better to add them.
Need tests / integration tests and docs.

2020-11-26 03:46 UTC, shumin1027 commented on src/sinks/redis.rs
> +use redis::{aio::ConnectionManager, AsyncCommands, RedisError, RedisFuture, RedisResult};
ConnectionManager implement the [ConnectionLike](https://docs.rs/redis/0.17.0/redis/aio/trait.ConnectionLike.html) trait and the Send & Sized trait ,so the `ConnectionManager` can be used as `AsyncCommands`
[AsyncCommands](https://docs.rs/redis/0.17.0/redis/trait.AsyncCommands.html)
[AsyncCommands Src](https://docs.rs/redis/0.17.0/src/redis/commands.rs.html#1975)
```rust
#[cfg(feature = "aio")]
impl<T> AsyncCommands for T where T: crate::aio::ConnectionLike + Send + Sized {}

```

2020-11-26 04:36 UTC, shumin1027 commented on src/sinks/redis.rs
> +        }
At first I planned also support `redis stream`， considering that  `redis stream` and `kafka` are very similar，
and I haven't particularly understood how to write a vector plugin，so I refer to the implementation of `kafka` and `pulsar`

2020-11-26 05:41 UTC, shumin1027 commented
@fanatid Thanks，I will add some tests / integration tests and docs

2020-11-26 09:18 UTC, shumin1027 commented
@fanatid I just started learning rust， not yet particularly familiar with the whole project and how to do integration testing，
I am currently maintaining this function(redis source and sink) myself, so I need to constantly update the code to adapt to the  code(vector) update，can you help me to let this function be better maintained ?

2020-11-26 10:05 UTC, fanatid commented
This code looks very good for a start with rust :slightly_smiling_face: we would happy to have redis source/sink in vector, do not hesitate to ask any rust / other questions on our discord server.
integration tests: it looks very similar to the usual tests but will need real redis for communication, I think a good example will be PR with nginx (https://github.com/timberio/vector/pull/5209/files `ctrl+f: integration` :smile:)
What do you think about split this PR into two: source and sink? I think we would able to finish components faster one by one than both in one place.

2020-11-27 01:39 UTC, jamtur01 commented
@shumin1027 You don't need to add yourself to CODEOWNERS - we generally handle that internally to the project. Thanks.

2020-11-27 04:33 UTC, shumin1027 commented
@fanatid  thanks for your guidance，I have add redis sink&source integration test

2020-12-01 17:01 UTC, jszwedko reviewed
This is great, thanks so much for the contribution @shumin1027.

I left some in-line comments below, mostly around logging and better handling of error conditions.

We should also add internal events for the sink as you did with the source.

I agree with @fanatid that splitting this into two PRs, one for the source and one for the sink may allow them to get merged more quickly. It's up to you though.

We will want to add cue-based docs (see `docs/` folder), but we can help with that when this is ready.

2020-12-01 17:05 UTC, fanatid commented on src/sinks/redis.rs
> +            encoding: Encoding::Json.into(),
+1 for `Encoding::Json` by default or remove default value at all. `Text` by default will be removed from sinks soon https://github.com/timberio/vector/pull/5281

2020-12-01 17:50 UTC, fanatid commented on src/sinks/redis.rs
> +                    while this.pending_acks.remove(&this.seq_tail) {
Example with A, B, C, D, E looks correct for me. What numbers of events for acking you would expect to see @jszwedko?

2020-12-01 20:40 UTC, jszwedko commented on src/sinks/redis.rs
> +                    while this.pending_acks.remove(&this.seq_tail) {
Sorry, I mean that they would ack in the wrong order. As far as I can tell, the acker just takes a number of messages to ack. I'm assuming (but need to verify) that it treats them in FIFO order. If Redis processes them in a different order we could end up acking a message in vector that hasn't actually been processed.

Imagine, in my example, that `vector` died after processing event C. If we had ack'd 1 every time, then B would have been ack'd even though it maybe was never successfully processed by redis. I think, in that case, we'd want to ideally keep it in the buffer and resend it when vector comes back up, even if that means re-sending event D too.

2020-12-02 14:05 UTC, fanatid commented on src/sinks/redis.rs
> +                    while this.pending_acks.remove(&this.seq_tail) {
@lukesteensen we can make `pending_acks` and acking more clear if change `FuturesUnordered` to `FuturesOrdered`, but I'm not sure will change slowing acking or not. Should we try?

2020-12-02 14:08 UTC, jszwedko commented on src/sinks/redis.rs
> +                    while this.pending_acks.remove(&this.seq_tail) {
:+1: I talked with @fanatid out-of-band about this. I didn't realize this was a pattern we were already using and I can see how `seq_head`/`seq_tail` keeps us acking in the right order.

I also agree that using `FuturesOrdered` would make this more clear. It seems to do what we want (run futures in parallel, but only resolve them in order).

2020-12-03 07:04 UTC, shumin1027 commented
@jszwedko @fanatid 
Thanks for your suggestions，let me know how to improve the code，I will try to split this into two PRs, one for the source and one for the sink

2021-01-02 17:19 UTC, binarylogic commented
@shumin1027 should we close this in favor of 2 separate PRs?

2021-01-04 06:06 UTC, shumin1027 commented
@binarylogic Ok, you can close this and I will push PRs for this two issues: 


- #5696 add redis source support 
- #5697 add redis sink support 

Thank you！

2021-03-12 15:25 UTC, leebenson commented
@shumin1027, just a quick update -- I've assigned myself as the reviewer for #5696 and #5697.

I don't currently have a firm ETA for review, but this is now on my radar and I'll keep you posted.

Many thanks for your contribution!

I'll go ahead and close this PR, given the separate source/sink PRs above. Thanks!

2021-03-12 15:25 UTC, closed without merging

2021-04-10 04:09 UTC, shumin1027 commented
@leebenson  
thank you ，I create a new  PR: #7078