chore(ci): Fix remap benches
timberio/vector pull request #5685
Opened 2020-12-22 18:47 UTC by jszwedko

Also adds them to CI so that we should catch it if they break again.

@FungusHumungus I'm not super confident with my fix to the `map` macro here. I'd appreciate your :eyes: 

The error I was resolving was:

```
error[E0277]: the trait bound `remap_lang::Value: From<remap_lang::expression::Map>` is not satisfied                                                                         
  --> benches/remap.rs:39:1                                                                                                                                                      |                                                                                   
39 | / bench_function! {                                                               
40 | |     parse_json => remap_functions::ParseJson;                                   
41 | |                                                                                                                                                                        
42 | |     literal_value {                                                             
...  |                                                                                 
53 | |     }                                                                                                                                                                  54 | | }                                                                               
   | |_^ the trait `From<remap_lang::expression::Map>` is not implemented for `remap_lang::Value`                                                                             
   |                                                                                   
   = help: the following implementations were found:                                   
             <remap_lang::Value as From<&[u8]>>                                                                                                                               
             <remap_lang::Value as From<&str>>                                                                                                                                
             <remap_lang::Value as From<()>>                                                                                                                                               <remap_lang::Value as From<BTreeMap<std::string::String, remap_lang::Value>>>                                                                                    
           and 15 others                                                               
   = note: required by `from`                                                                                                                                                 
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info) 
```

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

2020-12-22 21:18 UTC, FungusHumungus commented
Yeah, I've just noticed, along with @Hoverbear that there are currently 6 implementations of the `map!` macro in the project, and two of those do quite different things. So issues like this are bound to crop up..

2020-12-23 09:52 UTC, FungusHumungus requested changes
I've raised #5695 as this is an area that needs sorting out. It keeps tripping people up.

The changes to the `map!` macro need to be reverted as they are used elsewhere - ideally that macro should be deleted and those places need to be updated to use the new `value!` macro instead, but that's not for this issue..

Then instead of the line in `benches/remap.rs`:
```rust
 want: Ok(map!["key": "default"]),
```

it should be 

```rust
 want: Ok(value!({"key": "default"})),
```

2020-12-23 09:52 UTC, FungusHumungus commented on lib/remap-lang/src/test_util.rs
> -        let map = ::std::collections::BTreeMap::<String, $crate::Expr>::new();
These changes need to be reverted as it breaks things elsewhere.

2020-12-23 16:43 UTC, jszwedko commented
Thanks @FungusHumungus ! I made the changes you suggested.

2020-12-23 16:45 UTC, FungusHumungus approved these changes
Sweet, looks good! As long as CI is happy, I'm happy.

2020-12-23 18:35 UTC, merged