enhancement(performance): Adjust the strength of `gauge_add` atomics
timberio/vector pull request #6480
Opened 2021-02-17 20:15 UTC by blt

This commit adjusts the strength of the `gauge_add` atomics used by
`OpenGauge`. Previous implementation called `emitter` potentially `n^2 / 2`
times, where `n` is the number of participants. Current implementation calls
`emitter` only once after the participant CPU manages to adjust `OpenGauge`
value, though no guarantee is made about the ordering of participant calls to
`emitter`. That is, this commit guarantees that thread `A` will sequence its call
to `emitter` after modification of the internal `gauge` but makes no guarantee
about sequence of thread `B`'s parallel call to its `emitter`, relative to `A`.

If the point of this code is to sequence calls to `emitter` between threads we
can close this out and I'll make a different PR to clarify in the
documentation.

Closes #6477

2021-02-17 22:41 UTC, bruceg approved these changes
LGTM

2021-02-17 23:16 UTC, jszwedko approved these changes
Thanks @blt ! This looks good to me. I'm a bit confused why were were calling the `emitter` on every loop even before this change.

2021-02-18 11:54 UTC, ktff requested changes
> If the point of this code is to sequence calls to emitter between threads

Yep, that's goal. The main reason is to guarantee

>  but makes no guarantee
about sequence of thread B's parallel call to its emitter, relative to A.

since without it a gauge metric with older value can overwrite a gauge metric with newer value until a third update comes, which could take a while since connection aren't opened/closed all the time, and during that time internal metrics will report old value.

2021-02-18 16:40 UTC, blt commented
@ktff appreciate the clarification. Will address.

2021-02-18 18:08 UTC, blt commented
@ktff 5dbe9a7 should address your feedback. Please do take a look when you have a chance.

2021-02-18 18:40 UTC, ktff approved these changes
Nice, on the point, .... well it seams I'll need to write a book to gain this ability.

2021-02-18 18:40 UTC, ktff commented on src/internal_events/open.rs
> +                hint::spin_loop();
Nice

2021-02-18 21:42 UTC, blt commented on src/internal_events/open.rs
> +                hint::spin_loop();
:bow:

2021-02-19 00:25 UTC, merged