enhancement(kubernetes platform) Add ability to specify automountServiceAccountToken for vector-agent
timberio/vector pull request #6569
Opened 2021-02-26 23:26 UTC by joshuastern

Allow for specifying the automountServiceAccountToken field on the vector-agent service account.

2021-03-01 15:58 UTC, blt approved these changes
Makes sense to me. PR preserves the existing behavior and is a useful toggle to expose.

2021-03-02 15:39 UTC, eeyun approved these changes

2021-03-02 15:52 UTC, eeyun requested changes
@joshuastern if you wouldn't mind - to avoid our helm chart behaviors from getting out of sync of one another, can you apply this same patch to our aggregator chart? Doing so and then pushing should now also trigger the k8s e2e CI tests to validate we didn't introduce a regression.

2021-03-02 21:46 UTC, eeyun approved these changes
Looking good now. Thanks so much for the contribution!!

2021-03-03 15:07 UTC, merged