Add kubeval checks to helm chart updates
timberio/vector pull request #6649
Opened 2021-03-05 21:47 UTC by eeyun

Signed-off-by: Ian Henry <ianjhenry00@gmail.com>
Closes #6413

2021-05-11 15:19 UTC, spencergilbert requested changes
Longer term we should look to have a matrix of tests covering the kubernetes versions we advertise support for

2021-05-11 15:19 UTC, spencergilbert commented on scripts/helm-template-snapshot.sh
> +      kubeval "${TARGET_FILE}"
I suspect we'd want to use the `--strict` flag here, [docs](https://www.kubeval.com/#strict-schemas`

```suggestion
      kubeval --strict "${TARGET_FILE}"
```

2021-05-17 16:41 UTC, spencergilbert approved these changes

2021-05-17 17:40 UTC, jszwedko approved these changes

2021-05-17 19:29 UTC, merged