Additional labels for Prometheus Operator
timberio/vector pull request #7474
Opened 2021-05-15 16:54 UTC by nlamirault

* enhancement(podmonitor.yaml and values.yaml): Added additional labels feature for PodMonitor for Prometheus Operator.

2021-05-17 02:35 UTC, spencergilbert requested changes
Thanks @nlamirault definitely useful to allow - two suggested changes to the comments just for clarity.

2021-05-17 02:35 UTC, spencergilbert commented on distribution/helm/vector-agent/values.yaml
> +    # Additional labels for Prometheus Operator
```suggestion
    # Additional labels for PodMonitor
```

2021-05-17 02:35 UTC, spencergilbert commented on distribution/helm/vector-aggregator/values.yaml
> +    # Additional labels for Prometheus Operator
```suggestion
    # Additional labels for PodMonitor
```

2021-05-17 02:35 UTC, spencergilbert commented
@binarylogic should we add a `helm` scope for semantic PRs or is `Kubernetes platform` appropriate here?

2021-05-17 03:58 UTC, binarylogic commented
Yes, I would add it [here](https://github.com/timberio/resources/blob/master/vector/github/locals.tf#L174). That will sync it across everything.

2021-05-17 05:53 UTC, nlamirault commented
> Yes, I would add it [here](https://github.com/timberio/resources/blob/master/vector/github/locals.tf#L174). That will sync it across everything.

Link seems broken @binarylogic

2021-05-17 16:32 UTC, spencergilbert commented
> > Yes, I would add it [here](https://github.com/timberio/resources/blob/master/vector/github/locals.tf#L174). That will sync it across everything.
> 
> Link seems broken @binarylogic

Sorry @nlamirault that was for me, private config repo - I'm adding a `helm` platform option for the semantic PR check

2021-05-17 20:00 UTC, spencergilbert commented
@nlamirault after running down some rabbit holes... https://github.com/timberio/vector/blob/master/.github/semantic.yml#L79

2021-05-17 20:01 UTC, spencergilbert commented on distribution/helm/vector-aggregator/values.yaml
> +    # Additional labels for Prometheus Operator
I think with this it should be good to un-draft and go 😃

2021-05-31 13:29 UTC, JeanMertz approved these changes
LGTM once @spencergilbert's comment is resolved. 🙌

2021-06-01 14:50 UTC, spencergilbert approved these changes

2021-06-01 16:04 UTC, merged