feat(remap): add string comparison capability
timberio/vector pull request #7704
Opened 2021-06-02 09:02 UTC by jdrouet

Allow to compare strings

Signed-off-by: Jérémie Drouet <jeremie.drouet@datadoghq.com>

2021-06-02 13:01 UTC, JeanMertz requested changes
Awesome! 🙌  I left one remark.

Other than that, we should update the Cue docs to reflect this change in the language.

2021-06-02 15:13 UTC, jdrouet commented on lib/vrl/compiler/src/expression/op.rs
> +                .merge(rhs_def.fallible_unless(K::Bytes))
You're right, I did hesitate to put it or not. 👍

2021-06-02 15:25 UTC, JeanMertz requested changes

2021-06-02 15:25 UTC, JeanMertz commented on lib/vrl/compiler/src/expression/op.rs
> +                lhs_def.scalar(K::Boolean)
rhs can still be fallible, so we need to merge it with lhs:

```suggestion
                lhs_def.merge(rhs_def).boolean()
```

2021-06-02 15:25 UTC, JeanMertz commented on lib/vrl/compiler/src/expression/op.rs
> +                lhs_def.scalar(K::Boolean)
It would be good to add a test that captures this condition.

2021-06-02 15:58 UTC, jszwedko approved these changes
Nice work! I agree with Jean's remark about fallibility, but otherwise this looks good to me.

2021-06-03 08:29 UTC, JeanMertz requested changes
One more comment to resolve.

Also, I realized we don't have any integration tests for this change yet. Take a look at [this directory](https://github.com/timberio/vector/tree/master/lib/vrl/tests/tests/expressions/comparison) for more details.

2021-06-03 08:29 UTC, JeanMertz commented on lib/vrl/compiler/src/expression/op.rs
> +            expr: |_| op(Lt, "bar", "bar"),
```suggestion
            expr: |_| op(Le, "bar", "bar"),
```

2021-06-03 08:34 UTC, leebenson requested changes
This is looking great 👍🏻 

Just a couple of small additions:

1. To add to @JeanMertz's request for tests, I'd specifically like to see comparisons between mixed-case stings and comparing different locales. The immediate use-case outside of VRL is to allow for `{a TO c}` range translations from Datadog search syntax (per https://github.com/timberio/vector/pull/7633), so we should also assert that comparisons work identically to how they would at Datadog.
2. There are a few warnings about transforms not being used. Just an FYI to ensure all tests are passing.

2021-06-03 09:49 UTC, JeanMertz commented on lib/vrl/tests/tests/expressions/comparison/ge.vrl
> +    to_string([.foo]) >= "bar" ?? "nope",
We'll also want to fill out the matrix of all other possibilities.

E.g.

```
"a" > "b"
"a" > "a"
"b" > "a"
```

And do that for all comparison operators.

It's a bit of an annoyance to have to write those out manually, especially for the comparison expression, but it's good to cover our bases. (and also, as @leebenson suggested, it's also good to test a few more, such as `1 > "a"` etc).

2021-06-03 10:36 UTC, JeanMertz approved these changes
Sweet! LGTM 🙌

2021-06-04 13:51 UTC, jdrouet commented
Regarding the string comparison, datadog is using the unicode string comparison, [same as Rust](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2bb595521481fb63b7394a93fb19f04e).
I think it's good for this question. Regarding the CI warnings, after rebasing, it's fixed.

2021-06-04 13:52 UTC, leebenson approved these changes
🎉

2021-06-04 13:58 UTC, merged