enhancement(internal_logs source): Allow host_key and pid_key to be configured
timberio/vector pull request #8440
Opened 2021-07-23 17:52 UTC by jszwedko

Also allows for disabling via setting the key to `""`.

I'm still not crazy about these keys, but we don't have a better way to
handle it yet.

Partially addresses https://github.com/timberio/vector/issues/8407

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

2021-07-23 18:13 UTC, spencergilbert commented
> I'm still not crazy about these keys, but we don't have a better way to
handle it yet.

Do you have a "pie in the sky" idea?

2021-07-23 18:13 UTC, spencergilbert commented on docs/cue/reference/components/sources/internal_logs.cue
> +				default: "host"
Wouldn't this be `pid`?

2021-07-23 18:14 UTC, spencergilbert requested changes
default issue and the test failure - otherwise lgtm

2021-07-23 18:16 UTC, jszwedko commented on docs/cue/reference/components/sources/internal_logs.cue
> +				default: "host"
Doh, yes.

2021-07-26 19:45 UTC, spencergilbert approved these changes

2021-07-26 19:46 UTC, merged