fix(vector sink): retry on failed connection
timberio/vector pull request #8758
Opened 2021-08-17 05:25 UTC by JeanMertz

fixes #8648.

I'm unsure of the correct solution here. The fix as implemented in this PR works, but:

- I can't be sure there aren't any other potential error messages that go unnoticed and don't trigger a retry
- Should we instead always treat `Unknown` errors as retryable?
- Additionally, I'm not sure what the best way to test this is. How can I have it validate that it retried once, and then stop the test from endlessly retrying? Anyone have any suggestions?

2021-08-17 12:44 UTC, JeanMertz commented
> Should we instead always treat `Unknown` errors as retryable?

Actually, what I'm more curious about is if we have any guidelines on what types of error _should_ fail the component (and shut down Vector)?

For example, currently we also fail on internal server errors, or permission errors, but it could be reasoned that internal server errors are often temporarily, and permission errors _might_ be due to invalid credentials, but even so that can still be resolved on the server (e.g. by matching the credentials used by the client).

So really what I'm asking is, which types of errors should _never_ be retried, if any?

2021-08-17 14:20 UTC, spencergilbert commented
> > Should we instead always treat `Unknown` errors as retryable?
> 
> Actually, what I'm more curious about is if we have any guidelines on what types of error _should_ fail the component (and shut down Vector)?
> 
> For example, currently we also fail on internal server errors, or permission errors, but it could be reasoned that internal server errors are often temporarily, and permission errors _might_ be due to invalid credentials, but even so that can still be resolved on the server (e.g. by matching the credentials used by the client).
> 
> So really what I'm asking is, which types of errors should _never_ be retried, if any?

My gut instinct would be fail on permission errors, and retry (with backoff?) for internal server errors... that said I don't have any good reason why they should be different...

2021-08-17 20:53 UTC, jszwedko commented
Yeah, I'm inclined to agree with @spencergilbert that we shouldn't retry the equivalent of 400-level HTTP errors (that is, bad requests) which'll never succeed, but retry anything else. I'm happy to see us go with whatever the current `http` sink does though until we can revisit this more holistically.

I made a note on https://github.com/timberio/vector/issues/8728 to cover this topic there.

2021-08-17 20:57 UTC, spencergilbert commented
> Yeah, I'm inclined to agree with @spencergilbert that we shouldn't retry the equivalent of 400-level HTTP errors (that is, bad requests) which'll never succeed, but retry anything else. I'm happy to see us go with whatever the current `http` sink does though until we can revisit this more holistically.
> 
> I made a note on #8728 to cover this topic there.

Alternatively, I think the fact that we own both ends of this component we're free to handle however we see fit - which I think @JeanMertz mentioned during standup

2021-08-18 17:27 UTC, bruceg requested changes

2021-08-18 17:27 UTC, bruceg commented on src/sinks/vector/v2.rs
> +                Unknown | Internal | PermissionDenied => false,
I think `Internal` errors should definitely be retriable here, as they are reporting a potentially transient condition on the server. I _think_ `Unknown` should also be retriable, but it depends somewhat what all errors are grouped into this category.

2021-08-20 08:25 UTC, JeanMertz commented
This one should be good to go. @bruceg feel like giving it another look?

2021-08-20 15:12 UTC, bruceg approved these changes
LGTM

2021-08-20 15:12 UTC, merged